name: Setup
description: 'Installs node, driver dependencies, and builds source'

runs:
  using: composite
  steps:
    - run: echo "hey sweetie"
      shell: bash

    - run: |
        curl -sS -I -H "Authorization: Bearer ${{github.token}}" https://api.github.com/ | grep -i x-oauth-scopes
      shell: bash



